apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: "kubernetes.io/hostname"
  containers:
  - image: supergiantkir/animals:moose
    name: mysql
#    resources: {}
#  dnsPolicy: ClusterFirst
#  restartPolicy: Always
#status: {}
