apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - redis
        topologyKey: "kubernetes.io/hostname"
  containers:
  - image: supergiantkir/animals:moose
    name: redis
#    resources: {}
#  dnsPolicy: ClusterFirst
#  restartPolicy: Always
#status: {}
